baseurl: 'https://rudnkh.me'
minify: true
publishDir: 'docs'
permalinks:
  playing: /playing/:contentbasename/
  writeups: /writeups/:contentbasename/
  watching: /watching/:contentbasename/
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
params:
  cdn: '/images/'
